name: google_ddns_update
description: A sample command-line application.
version: 1.1.0
author: Pedro Carvalho <inceptus.p@live.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  args: ^1.6.0
  http: ^0.12.2

dev_dependencies:
  pedantic: ^1.9.2
