name: google_ddns_update
description: A command-line application to update Google Domains DDNS.
version: 1.1.1
author: Pedro Carvalho <inceptus.p@live.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.0.0
  http: ^0.13.1
